### PR TITLE
#27 #37 UML Added 

### PR DESCRIPTION
**Pull request by Pooja-Codes**
Added Sequence Diagrams for,
 #27 User Authentication
#37 Account Registration-Management

Reference for sequence diagram core notations,
[Read](https://www.geeksforgeeks.org/unified-modeling-language-uml-sequence-diagrams/) || [Watch](https://www.youtube.com/watch?v=pCK6prSq8aw) || [Help Read](https://sequencediagram.org/instructions.html)

Please Review!

### CODE REVIEW

**Review by adelaidemz — APPROVED** [review]

**Review by yalexublue — CHANGES_REQUESTED** [review]
Send out invite link would be better combine with parent account registration, I don't think it should be considered as a single epic. Also for the account recovery etc, that should not be available for #37, but instead it should be part of superuser epic #26.

**Comment by Pooja-Codes** [comment]
@yalexublue Invite student was included in parent registration previously. However, after discussion with @adelaidemz, we decided to make it separate as we will send the invite link to students only when parent request(up to 5). We will not provide 5 links altogether to parents at the time of registration instead we will check the request and decide.

Also @yalexublue , as you mentioned, account recovery etc, should be in #26 as superuser. But, I would like to share that #27 and #26 both support epic. The superuser can not handle account recovery (password reset) as the superuser is responsible for monitoring and banning/deleting. Think it like if you want to reset your password then you interact with the system, not with support! I still believe account recovery should be there as part of my epic #27.

**Comment by yalexublue** [comment]
> @yalexublue Invite student was included in parent registration previously. However, after discussion with @adelaidemz, we decided to make it separate as we will send the invite link to students only when parent request(up to 5). We will not provide 5 links altogether to parents at the time of registration instead we will check the request and decide.
> 
> Also @yalexublue , as you mentioned, account recovery etc, should be in #26 as superuser. But, I would like to share that #27 and #26 both support epic. The superuser can not handle account recovery (password reset) as the superuser is responsible for monitoring and banning/deleting. Think it like if you want to reset your password then you interact with the system, not with support! I still believe account recovery should be there as part of my epic #27.

If account recovery can be done by user, isn't it part of account management #37 instead #27? But I do think I meant different for account recovery, what I meant was for banned account to be recovered, what you meant is recover password, I we do need to distinguish these two things. I meant would it possible to you to combine uml diagrams for ONE epic together in this case, even it might look bigger.

**Comment by Pooja-Codes** [comment]
> > @yalexublue Invite student was included in parent registration previously. However, after discussion with @adelaidemz, we decided to make it separate as we will send the invite link to students only when parent request(up to 5). We will not provide 5 links altogether to parents at the time of registration instead we will check the request and decide.
> > Also @yalexublue , as you mentioned, account recovery etc, should be in #26 as superuser. But, I would like to share that #27 and #26 both support epic. The superuser can not handle account recovery (password reset) as the superuser is responsible for monitoring and banning/deleting. Think it like if you want to reset your password then you interact with the system, not with support! I still believe account recovery should be there as part of my epic #27.
> 
> If account recovery can be done by user, isn't it part of account management #37 instead #27? But I do think I meant different for account recovery, what I meant was for banned account to be recovered, what you meant is recover password, I we do need to distinguish these two things. I meant would it possible to you to combine uml diagrams for ONE epic together in this case, even it might look bigger.

I think it would be okay to keep the recovery diagram as no other team member build this recovery part. At the end, in high level analysis we will not mention the epic hashtags or name. @yalexublue

**Review by yalexublue — APPROVED** [review]
Let's merge it so we can start to build the ppt for the demo, and see how everything fit

**Pull request merged**
