### PR TITLE
Add Shortlist Deployment Diagram

### PR DESCRIPTION
**Pull request by waltage**
Two parts of an initial deployment diagram

1. Structure of each Shortlist container (docker images with sidecar model)
2. General structure of AWS deployment patterns

### CODE REVIEW

**Review by yalexublue — COMMENTED** [review]
Looking good! Could you go over this during the afternoon meeting before we merge this?

**Comment by waltage** [comment]
> Looking good! Could you go over this during the afternoon meeting before we merge this?

will do; I will also add a link to an upcoming PR that has a first round deployment scripts setup

**Comment by waltage** [comment]
FYI... 
Docker Container and build/deploy scripts (diagram 1) are located here:
https://github.com/gcivil-nyu-org/team-2-inperson/tree/72-deployment-skeletons

**Review by jainsvaibhav — APPROVED** [review]
LGTM! Great work! Thanks :)

**Comment by Pooja-Codes** [comment]
Looks good to me! but hard to understand :)

**Review by Pooja-Codes — APPROVED** [review]
Looks good!

**Review by yalexublue — APPROVED** [review]

**Pull request merged**
