### PR TITLE
#81 Shortlist Design Folder

### PR DESCRIPTION
**Pull request by Pooja-Codes**
The team can use the folder to design Shortlist Application.  
Location : team-2-inperson\src\design

Added important logo and its details.
[Click to View Logo-Light-Dark](https://poojapatel.my.canva.site/)

@adelaidemz and I will update this folder with our branches. Till then you can start your design using our logo.

### CODE REVIEW

**Review by waltage — CHANGES_REQUESTED** [review]
Please don't call this `auth-design`.  Instead, `/src/design/....` should be fine.

Also, we need to have a .gitignore file, and an OWNERS file at the root of this folder: `/src/design/.gitignore` etc.

For your reference, the main style sheets for the app are inside of: 
https://github.com/gcivil-nyu-org/team-2-inperson/tree/develop/src/frontend/shortlist/src/assets

And any assets like images or favicons would go inside of: 
https://github.com/gcivil-nyu-org/team-2-inperson/tree/develop/src/frontend/shortlist/public

**Comment by Pooja-Codes** [comment]
> Please don't call this `auth-design`. Instead, `/src/design/....` should be fine.
> 
> Also, we need to have a .gitignore file, and an OWNERS file at the root of this folder: `/src/design/.gitignore` etc.
> 
> For your reference, the main style sheets for the app are inside of: https://github.com/gcivil-nyu-org/team-2-inperson/tree/develop/src/frontend/shortlist/src/assets
> 
> And any assets like images or favicons would go inside of: https://github.com/gcivil-nyu-org/team-2-inperson/tree/develop/src/frontend/shortlist/public

The purpose/idea to build a design folder is to make application design authentic and team members can access design references from here.  The fronted public folder can have the images which we will add in our app frontend(actual).

Considering that in mind I don't feel to put images (here logo) in the frontend public folder as it is the reference for frontend creation.

All other changes are done! Have a look!

**Review by waltage — APPROVED** [review]
LGTM

**Review by adelaidemz — APPROVED** [review]

**Comment by waltage** [comment]
@Pooja-Codes can you remove this old branch now that it has been merged? 
Thanks!

**Pull request merged**
