### PR TITLE
added user registration, account verification by email, login, logo…

### PR DESCRIPTION
**Pull request by jainsvaibhav**
…ut, password reset via email

### CODE REVIEW

**Comment by waltage** [comment]
does this have our credentials in it again?

**Comment by jainsvaibhav** [comment]
> does this have our credentials in it again?

Could u clarify what you mean?

**Comment by waltage** [comment]
> > does this have our credentials in it again?
> 
> Could u clarify what you mean?

src/backend/server/.example.env

Line 4; Line 14

Does this actually have our keys in it or are these things asterisks and '<>' in that file?

yep, we are using our credentials. u just need to take the reference from .example.env and create a .env file by updating the credentials we have.

**Comment by waltage** [comment]
can you please convert this to a draft while we try to get it deployed; it's hard to signal which commit will represent final for re-review while we're in progress

**Comment by jainsvaibhav** [comment]
> can you please convert this to a draft while we try to get it deployed; it's hard to signal which commit will represent final for re-review while we're in progress

sure. i didn't know about drafts but just checkout out ur comment on team-2 channel about it.

**Comment by waltage** [comment]
I need to lint and setup the test, and then this will be ready to review

**Pull request merged**
